#include<iostream>
using namespace std;

int main(){
    //RAT IN A MAZE PROBLEM

    //2D ARRAY IS A MAZE

    //1 REPRESENTING OPEN PATH AND 0 REPRESENTING CLOSED PATH

    //APPROACH

    //FOUR POSSIBLE MOVEMENTS
        //MAKE THOSE MOVEMENTS
        //MAKE A VISTED ARRAY KI VOH ALREADY VISITED TOH NAHI HAI
        //BACLTRACK KARKE FALSE KARTE JAO

        //GFG PAR QUESN SOLVING


}