//ARRAYS


//MISSING ELEMENT IN A CONSECUTIVE ARRAY
//CHECK IF SUM OF FIRSTN NATURAL NOS. IS SAME OR NOT
//IF NOT SAME TOH SOMETHING IS MISSING
//USE A FOR LOOP TO GET THE SUM OF THE ARRAY N THEN SUBTRACT IT TO GET THE MISSING NO.
//OR TO FIND JUST USE THE AP  KA SUM FORMULA
//ALSOOOO
    //DIFFERENCE BETWEEN INDEX AND NO. IS ALSO SAME
    //MAKE SUCH OBSERVATIONS BASICALLY

//MULTIPLE MISSING ELEMENTS IN AN ARRAY
    //KEEP CHECKING WHERE DIFFERNECE IS NOT MATCHING
    //SIMPLE

//FINDING MISSING ELEMENTS
    //FASTER METHOD
    //MAKE NEW ARRAY PF BIGGER SIZE OF ZEROES
    //N FOR A ELEMENT GO TO USS VALUE KA INDEX AND INCREMENT IT
    //JAHAAN ZEROES BACHENGE VOH MISSING ELEMENTS
    //HASH TABLE OR BITSET KEHTE HAIN ISE

//FINDING DUPLICATES IN AN ARRAY
    //WHILE LOOP CHALA KAR CHECK W NEXT ELEMENT IF SAME OR NOT
    //PRINT N SHIT
    //TO COUNT CAN ALSO USE TWO PIOINTERS
    //BUT I FEEL CAN MAKE A WHILE LOOP N THEN JUST KEEP INCREMENTING COUNT WHEN WE FIND A DUPLICATE
    //BUT IF HAVE TO KEEP COUNT OF DISTINCT DUPLICATE THEN WILL HAVE TO USE TWO PINTERS FOR THE SAME

//FINDING DUPLICATES USING HASH TABLE
    //HAR INDEX PAR JO VALUE HAI USS INDEX KI VALUE KO DUSRE ARRAY KA INDEX BANA KAR KEEP INCREMENTING
    //JAHAAN INCREMENT KARKE VALUES ARE MORE THAN 1 VOH HO GAYE DUPLICATE ELEMENTS
    //ORDER OF N



