//SPARSE MATRIX
//STORING MATRIX IN LESS AMOUNT OF SPACE

//METHODS TO STORE THE NON ZERO ELEMENTS
    //COORDINATE LIST/ 3 COL REP
    //COMPRESSED SPARSE ROW

//3 COL REP
//3 COLS 
//ROW, COL, ELEMENT

//MAKE ARRAY FOR ROWS
//N FILL TH ARRAY AS CUMULATIVE APPEARANCE OF NON ZEROES IN THE ROWS
//MAKE COLUMN ARRAY
//WHERE YOU FILL ELEMENTS ACC TO THE IN WHICH COLUMN TH EELEEMNTS ARE PRESENT IN THE ARRAY HOLDING ELEMENTS

//ADDITION OF SPARSE MATRICES
//WEIRD SHIT
//ROW COL INT
//IN ANOTHER MATRIX ITSELF
//JUST TO DECREASE SPACE
//IN  THE ARRAY FIRST COL IS SIMPLY TOTAL NO OF ROWS, COLS, NON ZERO ELEEMTS

//ADDITION OF SPARSE MATRICES



//CREATING A SPARSE MATRIX

#include <iostream>
using namespace std;

struct element{
        int i;
        int j;
        int k;
    };
struct mat{
        int m;
        int n;
        int j;
        struct element *x;
        
    }
//INCOMPLTEE


