//STRINGS
//ASCII CODE
//UNICODES
//ASCII CODE FOR A=65
//AISE AISE AAGE AAGE 
//FOR NUMBERS ALSO ASCII CODES ARE THERE
//EVERYTHING ON THE KEYBOARD MAKES THE CHARACTER SET 
//CHARACTER SET CAN BE REPRESENTED IN ASCII

// FOR ENTER ASCII CODE=10
//SPACE ASCII CODE= 13
//0-127
//7 BITS ARE EFFICIENT

//ASCII CODES SUBSET OF UNICODES
//unicodes 16 bits
//4 SETS IF 4 BITS EACH

//CHAR TEMP; TEMP='A'
//STORES IT AS 65
//CHAR TAKES 1 BYTE

//'\0' TO MARK THE END OF THE STRING
//LENGTH OF STRING IS KNOWN BY FINDING THE ENDING CHARACTER

//to store 4 chars have to declare array for 5
//gets() helps you read entire string

//LENGTH OF A STRING 
//FOR LOOP CHALA KAR COUNTER A[I]!='\0' INCREMENT KARKE TILL \0

//CHANGING CASE FOR A STRING
//UPPERCASE TO LOWER CASE
//TOH NUMERIC ASCII REPRO MAI SAME DIFFERENCE
// FOR LOOP CHALA KAR HARR INDEX MAI ADD 32

//UPPERCASE 65-90
//LOWERCASE 97-122

//ABHI TAK WE ARAE MAKING STRINGS IN THE FORM OF ARRAY OF CHARACTERS

//VALIDATING A STRING
//ONLY ALPHABETS N NUMBERS
//NO SPECIAL CHARCATERS
    //!(range of capital n lowercase)

//REVERSING A STRING
    //MAKE A NEW ARRAY N COPY IT ULTA
    //dusra method
    //KEEP SWAPPING N FOR LOOP MAI CONDITION DAALSO !=\0
    //EK POINTER AAGE SE N EK PEECHE SE KEEP SWAPPING
    //SORT

//COMPARING STRINGS
    //EK FOR LOOP LAGAKAR JUST COMPARE SAB SIMPLY
    //SORTED

//PALINDROME
    //REVERSE SAME
    //bas tehn compare dono ko
    //SORTED
    //OR MAKE TWO POINTERS AAGE PEECHE N COMPARE
    
//DUPLICATE IN A STRING
    //HASH TABLE BANA DO?
    //YES; ASCII CODE USE KARNA
    //TWO FOR LOOPS CHALA KAR COMPARE EVERYTHING
    
    //ANOTHER NEW METHOD TO DO THE SAME IS 
    //BITWISE OPERATIONS
    //USEFUL FOR INTEGERS ALSO BUT CAN USE W STRINGS

    //1 BYTE LO
    //INDEXING ULTA CZ LSB TO MSB
