//WITHOUT DATA NO USE OF INSTRUCTIONS
 //EVERYTHING IS STORED IN THE HARD DISK AND WHEN RUNNING IT
 //IT GETS PULLED FROM THE HARD DISK TO THE MAIN MEMORY
 //DATA FOR THE APPLICATION IS BROUGHT INSIDE THE MAIN MEMORY 
 //NOW FOR EFFICIENT USE THE DATA IS ARRANGED IN A CERTAIN WAY THAT ARRANGING IS CALLED
 //DATA STRUCTURE
//DATA WAREHOUSE
    //THE OLD DATABASES FOR ANALYTICS 
    //THE QUERIES WRITTEN FOR IT N DATA TAKEN OUT IS DATA MINING
//BIG DATA
    //INTERNET'S DATA THAT'S GETTING COLLECTED

//MAIN MEMORY
    //3 SECTIONS
    //HEAP: DYNAMIC MEMORY ALLOCATION, PILING UP 
        //UNOORGANISED OR ORGANISED; SHOULD BE TAKEN A S ARESOURCE. NEED TO RELEASE MEMORY AFTER USE.
        //PROGRAM DOESN'T ACCESS DIRECTLY
        //USING POINTER CAN ACCESS
        //INT *P; P=NEW INT[5]; ALLOCATION
        //DELETE []P; P=NULL;  DEALLOCATION

    //STACK: STATIC MEMORY ALLOCATION, JAISE HI VARIABLE DECLARED VAISE HI MEMORY ALLOCATED
        //ACTIVATION RECORDS ARE MADE; ORGANISED
        //HAR FUNCTION JAB DECLARE KARTA HAI VARIABLES TOH EK SEGMENT KE UPAR EK AUR SSEGMENT OF ACTIVATION RECORDS ARE MADE
        //LOW KEY REPRESENTATING A STACK
        // NO EXTRA WORK NEEDS TI BE DONE BY THE PROGRAMMER TO ALLOCATE MEMORY 
    //CODE SECTION
    //INTEGER CAN TAKE 2 BYTES OR 4 BYTES DEPENDS ON THE COMPILER BUT GENERAL CASE 4 BYTES

//DATA STRUCTURES
//PHYSICAL AND LOGICAL
    //PHYSICAL
    //ARRAY
    //LINKED LIST ALWAYS CREATED IN HEAP
    //ARRAY IF SIZE IS KNOWN AND LINEKD LIST IF SIZE IS NOT KNOWN
    
    //LOGICAL  
     // HOW YOURE GOING TO PERFORM OPERATIONS ON THE PHYSICAL DATA STRUCTURES
     //LINEAR
     //STACK: LIFO
     //QUEUES: FIFO
        //NON LINEAR
        //TREES
        //GRAPHS
                //TABULAR
                //HASH TABLE

//ADT
//ABSTRACT DATATYPE
// 1 BYTE IS 8 BITS LOL
//DATA TYPE EXPLAINS AS
    //REPRESENTATION OF DATA AND OPERATION ON DATA
//ABSTRACT: HIDDEN DETAILS

//ADT: FOR OOPS, WITHOUT KNOWING DETAILS WE CAN USE THEM
//BASICALLY DESCRIBED BY A CLASS

//TIME AND SPACE COMPLEXITY
 //TIME DEPENDS ON THE PROCEDURE WE TAKE
